version: 2

cache_key: &cache_key
  key: jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "buildSrc/src/main/java/hoot/Deps.kt" }}-{{ checksum "build.gradle" }}

jobs:
  check:
    working_directory: ~/hoot
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          <<: *cache_key

      - run:
          name: Generate changelog
          command: ./gradlew generateChangelog
      - store_artifacts:
          path: app/build/reports/

      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

  deploy:
    working_directory: ~/hoot
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          <<: *cache_key

      - run:
          name: Generate changelog
          command: ./gradlew generateChangelog

workflows:
  version: 2
  check_deploy:
    jobs:
      - check:
         filters:
           branches:
             only:
               - master
               - /release-.*/
               - changelog
      - deploy:
         requires:
           - check
         filters:
           branches:
             only:
               - master
               - /release-.*/
               - changelog
